export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          email: string | null;
          role: "user" | "super_admin" | "full_admin" | "product_manager" | "orders_manager" | "customer_support" | "marketing_content_manager" | "finance_ledger" | "staff" | "admin" | "owner" | string;
          wallet_address: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          email?: string | null;
          role?: "user" | "super_admin" | "full_admin" | "product_manager" | "orders_manager" | "customer_support" | "marketing_content_manager" | "finance_ledger" | "staff" | "admin" | "owner" | string;
          wallet_address?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          email?: string | null;
          role?: "user" | "super_admin" | "full_admin" | "product_manager" | "orders_manager" | "customer_support" | "marketing_content_manager" | "finance_ledger" | "staff" | "admin" | "owner" | string;
          wallet_address?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      admin_settings: {
        Row: {
          key: string;
          value: Json;
          updated_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          key: string;
          value?: Json;
          updated_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          key?: string;
          value?: Json;
          updated_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      admin_notifications: {
        Row: {
          id: string;
          type: string;
          channel: "email" | "sms" | "push" | string;
          title: string;
          message: string;
          status: "queued" | "sent" | "skipped" | "failed" | "delayed" | string;
          href: string | null;
          dedupe_key: string;
          metadata: Json;
          read_at: string | null;
          delivered_at: string | null;
          error_message: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          type: string;
          channel: "email" | "sms" | "push" | string;
          title: string;
          message: string;
          status?: "queued" | "sent" | "skipped" | "failed" | "delayed" | string;
          href?: string | null;
          dedupe_key: string;
          metadata?: Json;
          read_at?: string | null;
          delivered_at?: string | null;
          error_message?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          type?: string;
          channel?: "email" | "sms" | "push" | string;
          title?: string;
          message?: string;
          status?: "queued" | "sent" | "skipped" | "failed" | "delayed" | string;
          href?: string | null;
          dedupe_key?: string;
          metadata?: Json;
          read_at?: string | null;
          delivered_at?: string | null;
          error_message?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      customers: {
        Row: {
          id: string;
          full_name: string;
          email: string;
          phone_country_code: string;
          phone_number: string;
          date_of_birth: string | null;
          customer_type: string;
          source: string;
          customer_group: string;
          vip_level: string;
          referral_by: string;
          address_line1: string;
          address_line2: string;
          city: string;
          state_province: string;
          postal_code: string;
          country: string;
          account_status: string;
          email_verification: string;
          has_account_access: boolean;
          subscription_status: string;
          subscribed_on: string | null;
          tags: Json;
          notes: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          full_name: string;
          email: string;
          phone_country_code?: string;
          phone_number?: string;
          date_of_birth?: string | null;
          customer_type?: string;
          source?: string;
          customer_group?: string;
          vip_level?: string;
          referral_by?: string;
          address_line1?: string;
          address_line2?: string;
          city?: string;
          state_province?: string;
          postal_code?: string;
          country?: string;
          account_status?: string;
          email_verification?: string;
          has_account_access?: boolean;
          subscription_status?: string;
          subscribed_on?: string | null;
          tags?: Json;
          notes?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          full_name?: string;
          email?: string;
          phone_country_code?: string;
          phone_number?: string;
          date_of_birth?: string | null;
          customer_type?: string;
          source?: string;
          customer_group?: string;
          vip_level?: string;
          referral_by?: string;
          address_line1?: string;
          address_line2?: string;
          city?: string;
          state_province?: string;
          postal_code?: string;
          country?: string;
          account_status?: string;
          email_verification?: string;
          has_account_access?: boolean;
          subscription_status?: string;
          subscribed_on?: string | null;
          tags?: Json;
          notes?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      products: {
        Row: {
          id: string;
          name: string;
          brand: string;
          description: string;
          price_php_cents: number;
          department: string;
          category_label: string;
          main_image_url: string;
          hover_image_url: string | null;
          gallery_image_urls: Json;
          size_inventory: Json;
          status: string;
          show_in_new_arrivals: boolean;
          show_in_featured: boolean;
          published_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          name: string;
          brand: string;
          description?: string;
          price_php_cents?: number;
          department?: string;
          category_label?: string;
          main_image_url: string;
          hover_image_url?: string | null;
          gallery_image_urls?: Json;
          size_inventory?: Json;
          status?: string;
          show_in_new_arrivals?: boolean;
          show_in_featured?: boolean;
          published_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          brand?: string;
          description?: string;
          price_php_cents?: number;
          department?: string;
          category_label?: string;
          main_image_url?: string;
          hover_image_url?: string | null;
          gallery_image_urls?: Json;
          size_inventory?: Json;
          status?: string;
          show_in_new_arrivals?: boolean;
          show_in_featured?: boolean;
          published_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      collections: {
        Row: {
          id: string;
          name: string;
          slug: string;
          description: string;
          image_url: string | null;
          status: string;
          collection_type: string;
          display_order: number;
          is_featured: boolean;
          featured_from: string | null;
          featured_until: string | null;
          meta_title: string;
          meta_description: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          slug: string;
          description?: string;
          image_url?: string | null;
          status?: string;
          collection_type?: string;
          display_order?: number;
          is_featured?: boolean;
          featured_from?: string | null;
          featured_until?: string | null;
          meta_title?: string;
          meta_description?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          slug?: string;
          description?: string;
          image_url?: string | null;
          status?: string;
          collection_type?: string;
          display_order?: number;
          is_featured?: boolean;
          featured_from?: string | null;
          featured_until?: string | null;
          meta_title?: string;
          meta_description?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      reviews: {
        Row: {
          id: string;
          product_id: string;
          order_id: string | null;
          customer_key: string;
          customer_name: string;
          customer_email: string | null;
          title: string;
          content: string;
          rating: number;
          status: string;
          is_featured: boolean;
          is_verified_purchase: boolean;
          name_display: string;
          media_urls: Json;
          submitted_at: string;
          moderation_notes: string;
          experience_feedback: string;
          source: string;
          review_request_sent_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          product_id: string;
          order_id?: string | null;
          customer_key: string;
          customer_name: string;
          customer_email?: string | null;
          title?: string;
          content: string;
          rating: number;
          status?: string;
          is_featured?: boolean;
          is_verified_purchase?: boolean;
          name_display?: string;
          media_urls?: Json;
          submitted_at?: string;
          moderation_notes?: string;
          experience_feedback?: string;
          source?: string;
          review_request_sent_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          product_id?: string;
          order_id?: string | null;
          customer_key?: string;
          customer_name?: string;
          customer_email?: string | null;
          title?: string;
          content?: string;
          rating?: number;
          status?: string;
          is_featured?: boolean;
          is_verified_purchase?: boolean;
          name_display?: string;
          media_urls?: Json;
          submitted_at?: string;
          moderation_notes?: string;
          experience_feedback?: string;
          source?: string;
          review_request_sent_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      blog_posts: {
        Row: {
          id: string;
          title: string;
          slug: string;
          excerpt: string;
          featured_image_url: string | null;
          content: string;
          status: string;
          visibility: string;
          categories: Json;
          tags: Json;
          author_name: string;
          publish_at: string | null;
          meta_title: string;
          meta_description: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          title: string;
          slug: string;
          excerpt?: string;
          featured_image_url?: string | null;
          content?: string;
          status?: string;
          visibility?: string;
          categories?: Json;
          tags?: Json;
          author_name?: string;
          publish_at?: string | null;
          meta_title?: string;
          meta_description?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          title?: string;
          slug?: string;
          excerpt?: string;
          featured_image_url?: string | null;
          content?: string;
          status?: string;
          visibility?: string;
          categories?: Json;
          tags?: Json;
          author_name?: string;
          publish_at?: string | null;
          meta_title?: string;
          meta_description?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      site_pages: {
        Row: {
          id: string;
          title: string;
          slug: string;
          page_type: string;
          parent_page_id: string | null;
          meta_description: string;
          content: string;
          featured_image_url: string | null;
          status: string;
          visibility: string;
          template: string;
          show_in_navigation: boolean;
          display_order: number;
          meta_title: string;
          meta_keywords: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          title: string;
          slug: string;
          page_type?: string;
          parent_page_id?: string | null;
          meta_description?: string;
          content?: string;
          featured_image_url?: string | null;
          status?: string;
          visibility?: string;
          template?: string;
          show_in_navigation?: boolean;
          display_order?: number;
          meta_title?: string;
          meta_keywords?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          title?: string;
          slug?: string;
          page_type?: string;
          parent_page_id?: string | null;
          meta_description?: string;
          content?: string;
          featured_image_url?: string | null;
          status?: string;
          visibility?: string;
          template?: string;
          show_in_navigation?: boolean;
          display_order?: number;
          meta_title?: string;
          meta_keywords?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      banners: {
        Row: {
          id: string;
          title: string;
          banner_type: string;
          link_url: string | null;
          link_target: string;
          priority: number;
          display_order: number;
          image_url: string | null;
          mobile_image_url: string | null;
          heading: string;
          subheading: string;
          description: string;
          button_text: string;
          button_style: string;
          status: string;
          visibility: string;
          display_on: string;
          device: string;
          starts_at: string | null;
          ends_at: string | null;
          show_homepage_only: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          title: string;
          banner_type?: string;
          link_url?: string | null;
          link_target?: string;
          priority?: number;
          display_order?: number;
          image_url?: string | null;
          mobile_image_url?: string | null;
          heading?: string;
          subheading?: string;
          description?: string;
          button_text?: string;
          button_style?: string;
          status?: string;
          visibility?: string;
          display_on?: string;
          device?: string;
          starts_at?: string | null;
          ends_at?: string | null;
          show_homepage_only?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          title?: string;
          banner_type?: string;
          link_url?: string | null;
          link_target?: string;
          priority?: number;
          display_order?: number;
          image_url?: string | null;
          mobile_image_url?: string | null;
          heading?: string;
          subheading?: string;
          description?: string;
          button_text?: string;
          button_style?: string;
          status?: string;
          visibility?: string;
          display_on?: string;
          device?: string;
          starts_at?: string | null;
          ends_at?: string | null;
          show_homepage_only?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      banner_events: {
        Row: {
          id: string;
          banner_id: string;
          event_type: string;
          location: string;
          path: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          banner_id: string;
          event_type: string;
          location?: string;
          path?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          banner_id?: string;
          event_type?: string;
          location?: string;
          path?: string;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "banner_events_banner_id_fkey";
            columns: ["banner_id"];
            referencedRelation: "banners";
            referencedColumns: ["id"];
          },
        ];
      };
      coupons: {
        Row: {
          id: string;
          code: string;
          name: string;
          description: string;
          coupon_type: "percentage" | "fixed_amount" | "free_shipping" | string;
          discount_value: string;
          minimum_purchase_amount: string;
          status: "active" | "disabled" | string;
          starts_at: string | null;
          ends_at: string | null;
          assigned_user_id: string | null;
          assigned_customer_email: string | null;
          usage_limit: number | null;
          usage_limit_per_customer: number | null;
          applicable_collection_slugs: Json;
          applicable_product_ids: Json;
          stackable: boolean;
          apply_to_sale_items: boolean;
          free_shipping: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          code: string;
          name?: string;
          description?: string;
          coupon_type?: "percentage" | "fixed_amount" | "free_shipping" | string;
          discount_value?: string;
          minimum_purchase_amount?: string;
          status?: "active" | "disabled" | string;
          starts_at?: string | null;
          ends_at?: string | null;
          assigned_user_id?: string | null;
          assigned_customer_email?: string | null;
          usage_limit?: number | null;
          usage_limit_per_customer?: number | null;
          applicable_collection_slugs?: Json;
          applicable_product_ids?: Json;
          stackable?: boolean;
          apply_to_sale_items?: boolean;
          free_shipping?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          code?: string;
          name?: string;
          description?: string;
          coupon_type?: "percentage" | "fixed_amount" | "free_shipping" | string;
          discount_value?: string;
          minimum_purchase_amount?: string;
          status?: "active" | "disabled" | string;
          starts_at?: string | null;
          ends_at?: string | null;
          assigned_user_id?: string | null;
          assigned_customer_email?: string | null;
          usage_limit?: number | null;
          usage_limit_per_customer?: number | null;
          applicable_collection_slugs?: Json;
          applicable_product_ids?: Json;
          stackable?: boolean;
          apply_to_sale_items?: boolean;
          free_shipping?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      campaigns: {
        Row: {
          id: string;
          name: string;
          campaign_type: string;
          goal: string;
          description: string;
          status: "draft" | "active" | "scheduled" | "paused" | "completed" | "disabled" | string;
          starts_at: string | null;
          ends_at: string | null;
          budget_amount: string | null;
          daily_budget_amount: string | null;
          tags: Json;
          channels: Json;
          audience_type: string;
          audience: string;
          track_conversions: boolean;
          ab_test_enabled: boolean;
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          campaign_type?: string;
          goal?: string;
          description?: string;
          status?: "draft" | "active" | "scheduled" | "paused" | "completed" | "disabled" | string;
          starts_at?: string | null;
          ends_at?: string | null;
          budget_amount?: string | null;
          daily_budget_amount?: string | null;
          tags?: Json;
          channels?: Json;
          audience_type?: string;
          audience?: string;
          track_conversions?: boolean;
          ab_test_enabled?: boolean;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          campaign_type?: string;
          goal?: string;
          description?: string;
          status?: "draft" | "active" | "scheduled" | "paused" | "completed" | "disabled" | string;
          starts_at?: string | null;
          ends_at?: string | null;
          budget_amount?: string | null;
          daily_budget_amount?: string | null;
          tags?: Json;
          channels?: Json;
          audience_type?: string;
          audience?: string;
          track_conversions?: boolean;
          ab_test_enabled?: boolean;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      orders: {
        Row: {
          id: string;
          order_number: string | null;
          user_id: string | null;
          email: string | null;
          product_id: string | null;
          product_name: string | null;
          selected_size: string | null;
          quantity: number;
          unit_price: string;
          customer_name: string;
          phone: string;
          shipping_address: string;
          shipping_address_line1: string | null;
          shipping_city: string | null;
          shipping_province: string | null;
          shipping_postal_code: string | null;
          shipping_country: string | null;
          shipping_zone: string | null;
          shipping_method: string | null;
          shipping_fee: string | null;
          delivery_latitude: string | null;
          delivery_longitude: string | null;
          delivery_place_id: string | null;
          delivery_map_provider: string | null;
          delivery_address_components: Json;
          subtotal_amount: string | null;
          tax_amount: string | null;
          tax_rate_label: string | null;
          tax_rate_percent: string | null;
          tax_breakdown: Json;
          coupon_id: string | null;
          coupon_code: string | null;
          discount_amount: string;
          discount_breakdown: Json;
          source: string | null;
          medium: string | null;
          campaign_id: string | null;
          campaign_name: string | null;
          utm_source: string | null;
          utm_medium: string | null;
          utm_campaign: string | null;
          attribution_data: Json;
          amount: string;
          currency: string;
          status: string;
          notes: string | null;
          confirmation_email_status: string;
          confirmation_email_sent_at: string | null;
          cancelled_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          order_number?: string | null;
          user_id?: string | null;
          email?: string | null;
          product_id?: string | null;
          product_name?: string | null;
          selected_size?: string | null;
          quantity?: number;
          unit_price?: string;
          customer_name?: string;
          phone?: string;
          shipping_address?: string;
          shipping_address_line1?: string | null;
          shipping_city?: string | null;
          shipping_province?: string | null;
          shipping_postal_code?: string | null;
          shipping_country?: string | null;
          shipping_zone?: string | null;
          shipping_method?: string | null;
          shipping_fee?: string | null;
          delivery_latitude?: string | number | null;
          delivery_longitude?: string | number | null;
          delivery_place_id?: string | null;
          delivery_map_provider?: string | null;
          delivery_address_components?: Json;
          subtotal_amount?: string | null;
          tax_amount?: string | null;
          tax_rate_label?: string | null;
          tax_rate_percent?: string | null;
          tax_breakdown?: Json;
          coupon_id?: string | null;
          coupon_code?: string | null;
          discount_amount?: string;
          discount_breakdown?: Json;
          source?: string | null;
          medium?: string | null;
          campaign_id?: string | null;
          campaign_name?: string | null;
          utm_source?: string | null;
          utm_medium?: string | null;
          utm_campaign?: string | null;
          attribution_data?: Json;
          amount: string;
          currency?: string;
          status?: string;
          notes?: string | null;
          confirmation_email_status?: string;
          confirmation_email_sent_at?: string | null;
          cancelled_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          order_number?: string | null;
          user_id?: string | null;
          email?: string | null;
          product_id?: string | null;
          product_name?: string | null;
          selected_size?: string | null;
          quantity?: number;
          unit_price?: string;
          customer_name?: string;
          phone?: string;
          shipping_address?: string;
          shipping_address_line1?: string | null;
          shipping_city?: string | null;
          shipping_province?: string | null;
          shipping_postal_code?: string | null;
          shipping_country?: string | null;
          shipping_zone?: string | null;
          shipping_method?: string | null;
          shipping_fee?: string | null;
          delivery_latitude?: string | number | null;
          delivery_longitude?: string | number | null;
          delivery_place_id?: string | null;
          delivery_map_provider?: string | null;
          delivery_address_components?: Json;
          subtotal_amount?: string | null;
          tax_amount?: string | null;
          tax_rate_label?: string | null;
          tax_rate_percent?: string | null;
          tax_breakdown?: Json;
          coupon_id?: string | null;
          coupon_code?: string | null;
          discount_amount?: string;
          discount_breakdown?: Json;
          source?: string | null;
          medium?: string | null;
          campaign_id?: string | null;
          campaign_name?: string | null;
          utm_source?: string | null;
          utm_medium?: string | null;
          utm_campaign?: string | null;
          attribution_data?: Json;
          amount?: string;
          currency?: string;
          status?: string;
          notes?: string | null;
          confirmation_email_status?: string;
          confirmation_email_sent_at?: string | null;
          cancelled_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      order_items: {
        Row: {
          id: string;
          order_id: string;
          product_id: string | null;
          product_name: string;
          product_brand: string | null;
          selected_size: string | null;
          quantity: number;
          unit_price: string;
          line_total: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          order_id: string;
          product_id?: string | null;
          product_name: string;
          product_brand?: string | null;
          selected_size?: string | null;
          quantity?: number;
          unit_price?: string;
          line_total?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          order_id?: string;
          product_id?: string | null;
          product_name?: string;
          product_brand?: string | null;
          selected_size?: string | null;
          quantity?: number;
          unit_price?: string;
          line_total?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      coupon_redemptions: {
        Row: {
          id: string;
          coupon_id: string;
          coupon_code: string;
          order_id: string | null;
          user_id: string | null;
          customer_email: string | null;
          discount_amount: string;
          product_discount_amount: string;
          shipping_discount_amount: string;
          order_subtotal_amount: string;
          order_total_before_discount: string;
          order_total_after_discount: string;
          status: "applied" | "cancelled" | "refunded" | string;
          metadata: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          coupon_id: string;
          coupon_code: string;
          order_id?: string | null;
          user_id?: string | null;
          customer_email?: string | null;
          discount_amount?: string;
          product_discount_amount?: string;
          shipping_discount_amount?: string;
          order_subtotal_amount?: string;
          order_total_before_discount?: string;
          order_total_after_discount?: string;
          status?: "applied" | "cancelled" | "refunded" | string;
          metadata?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          coupon_id?: string;
          coupon_code?: string;
          order_id?: string | null;
          user_id?: string | null;
          customer_email?: string | null;
          discount_amount?: string;
          product_discount_amount?: string;
          shipping_discount_amount?: string;
          order_subtotal_amount?: string;
          order_total_before_discount?: string;
          order_total_after_discount?: string;
          status?: "applied" | "cancelled" | "refunded" | string;
          metadata?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      fund_allocation_rules: {
        Row: {
          id: string;
          code: string;
          name: string;
          description: string | null;
          color: string;
          percentage_basis_points: number;
          display_order: number;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          code: string;
          name: string;
          description?: string | null;
          color?: string;
          percentage_basis_points: number;
          display_order?: number;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          code?: string;
          name?: string;
          description?: string | null;
          color?: string;
          percentage_basis_points?: number;
          display_order?: number;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      payment_allocations: {
        Row: {
          id: string;
          payment_id: string;
          allocation_rule_id: string | null;
          allocation_code: string;
          allocation_name: string;
          allocation_description: string | null;
          allocation_color: string;
          percentage_basis_points: number;
          base_amount: string;
          currency: string;
          allocated_amount: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          payment_id: string;
          allocation_rule_id?: string | null;
          allocation_code: string;
          allocation_name: string;
          allocation_description?: string | null;
          allocation_color?: string;
          percentage_basis_points: number;
          base_amount?: string;
          currency: string;
          allocated_amount?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          payment_id?: string;
          allocation_rule_id?: string | null;
          allocation_code?: string;
          allocation_name?: string;
          allocation_description?: string | null;
          allocation_color?: string;
          percentage_basis_points?: number;
          base_amount?: string;
          currency?: string;
          allocated_amount?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      admin_cash_outs: {
        Row: {
          id: string;
          request_id: string;
          created_by: string;
          payment_method: string;
          chain_id: number;
          source_mode: string;
          source_allocation_code: string | null;
          source_allocation_name: string | null;
          amount: string;
          amount_input_mode: string;
          amount_php_equivalent: string | null;
          quote_php_per_eth: string | null;
          quote_source: string | null;
          quote_updated_at: string | null;
          sender_wallet_address: string;
          destination_wallet_address: string;
          tx_hash: string;
          available_before: string;
          available_after: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          request_id: string;
          created_by: string;
          payment_method: string;
          chain_id?: number;
          source_mode?: string;
          source_allocation_code?: string | null;
          source_allocation_name?: string | null;
          amount: string;
          amount_input_mode?: string;
          amount_php_equivalent?: string | null;
          quote_php_per_eth?: string | null;
          quote_source?: string | null;
          quote_updated_at?: string | null;
          sender_wallet_address: string;
          destination_wallet_address: string;
          tx_hash: string;
          available_before?: string;
          available_after?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          request_id?: string;
          created_by?: string;
          payment_method?: string;
          chain_id?: number;
          source_mode?: string;
          source_allocation_code?: string | null;
          source_allocation_name?: string | null;
          amount?: string;
          amount_input_mode?: string;
          amount_php_equivalent?: string | null;
          quote_php_per_eth?: string | null;
          quote_source?: string | null;
          quote_updated_at?: string | null;
          sender_wallet_address?: string;
          destination_wallet_address?: string;
          tx_hash?: string;
          available_before?: string;
          available_after?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      admin_cash_out_breakdowns: {
        Row: {
          id: string;
          cash_out_id: string;
          allocation_rule_id: string | null;
          allocation_code: string;
          allocation_name: string;
          allocation_color: string;
          amount: string;
          available_before: string;
          available_after: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          cash_out_id: string;
          allocation_rule_id?: string | null;
          allocation_code: string;
          allocation_name: string;
          allocation_color?: string;
          amount?: string;
          available_before?: string;
          available_after?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          cash_out_id?: string;
          allocation_rule_id?: string | null;
          allocation_code?: string;
          allocation_name?: string;
          allocation_color?: string;
          amount?: string;
          available_before?: string;
          available_after?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      payments: {
        Row: {
          id: string;
          order_id: string | null;
          user_id: string | null;
          payment_method: string;
          payment_type: string | null;
          wallet_provider: string | null;
          network: string | null;
          token_type: string | null;
          token_standard: string | null;
          tx_hash: string | null;
          signature: string | null;
          wallet_address: string | null;
          sender_wallet_address: string | null;
          recipient_address: string | null;
          chain_id: number | null;
          amount_expected: string;
          amount_expected_fiat: string | null;
          fiat_currency: string | null;
          conversion_rate: string | null;
          usd_conversion_rate: string | null;
          coingecko_crypto_price: string | null;
          binance_crypto_price: string | null;
          price_difference_percent: string | null;
          slippage_buffer_percent: string | null;
          base_crypto_amount: string | null;
          slippage_buffer_amount: string | null;
          quote_source: string | null;
          quote_updated_at: string | null;
          quote_expires_at: string | null;
          amount_received: string | null;
          status: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          order_id?: string | null;
          user_id?: string | null;
          payment_method?: string;
          payment_type?: string | null;
          wallet_provider?: string | null;
          network?: string | null;
          token_type?: string | null;
          token_standard?: string | null;
          tx_hash?: string | null;
          signature?: string | null;
          wallet_address?: string | null;
          sender_wallet_address?: string | null;
          recipient_address?: string | null;
          chain_id?: number | null;
          amount_expected: string;
          amount_expected_fiat?: string | null;
          fiat_currency?: string | null;
          conversion_rate?: string | null;
          usd_conversion_rate?: string | null;
          coingecko_crypto_price?: string | null;
          binance_crypto_price?: string | null;
          price_difference_percent?: string | null;
          slippage_buffer_percent?: string | null;
          base_crypto_amount?: string | null;
          slippage_buffer_amount?: string | null;
          quote_source?: string | null;
          quote_updated_at?: string | null;
          quote_expires_at?: string | null;
          amount_received?: string | null;
          status?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          order_id?: string | null;
          user_id?: string | null;
          payment_method?: string;
          payment_type?: string | null;
          wallet_provider?: string | null;
          network?: string | null;
          token_type?: string | null;
          token_standard?: string | null;
          tx_hash?: string | null;
          signature?: string | null;
          wallet_address?: string | null;
          sender_wallet_address?: string | null;
          recipient_address?: string | null;
          chain_id?: number | null;
          amount_expected?: string;
          amount_expected_fiat?: string | null;
          fiat_currency?: string | null;
          conversion_rate?: string | null;
          usd_conversion_rate?: string | null;
          coingecko_crypto_price?: string | null;
          binance_crypto_price?: string | null;
          price_difference_percent?: string | null;
          slippage_buffer_percent?: string | null;
          base_crypto_amount?: string | null;
          slippage_buffer_amount?: string | null;
          quote_source?: string | null;
          quote_updated_at?: string | null;
          quote_expires_at?: string | null;
          amount_received?: string | null;
          status?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
    };
    Views: Record<string, never>;
    Functions: {
      finalize_verified_payment: {
        Args: {
          p_payment_id: string;
          p_tx_hash: string;
          p_wallet_address: string;
          p_recipient_address: string;
          p_chain_id: number;
          p_amount_received: string;
        };
        Returns: Json;
      };
      rebuild_payment_allocations: {
        Args: {
          target_payment_id: string;
        };
        Returns: undefined;
      };
      record_admin_cash_out_transfer: {
        Args: {
          p_amount: string;
          p_payment_method: string;
          p_request_id: string;
          p_created_by: string;
          p_chain_id: number;
          p_source_mode: string;
          p_source_allocation_code?: string | null;
          p_amount_input_mode?: string;
          p_amount_php_equivalent?: string | null;
          p_quote_php_per_eth?: string | null;
          p_quote_source?: string | null;
          p_quote_updated_at?: string | null;
          p_sender_wallet_address: string;
          p_destination_wallet_address: string;
          p_tx_hash: string;
        };
        Returns: Json;
      };
    };
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
};
