import Link from "next/link";
import { Download } from "lucide-react";

import type { ReportDefinition, ReportRangeKey } from "@/lib/admin/reports";

type Props = {
  rows: ReportDefinition[];
  rangeKey: ReportRangeKey;
};

function buildExportHref(tab: ReportDefinition["id"], range: ReportRangeKey) {
  return `/api/admin/reports/export?tab=${encodeURIComponent(tab)}&range=${encodeURIComponent(range)}`;
}

export function AdminRecentReportsTable({ rows, rangeKey }: Props) {
  return (
    <div className="vh-admin-report-table-wrap">
      <table className="vh-admin-report-table">
        <thead>
          <tr>
            <th>Report Name</th>
            <th>Type</th>
            <th>Date Range</th>
            <th>Generated On</th>
            <th>Generated By</th>
            <th>Format</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          {rows.map((row) => (
            <tr key={row.id}>
              <td>{row.name}</td>
              <td>{row.type}</td>
              <td>{row.dateRange}</td>
              <td>{row.generatedOn}</td>
              <td>{row.generatedBy}</td>
              <td>{row.format}</td>
              <td>
                <Link className="vh-admin-report-icon-button" href={buildExportHref(row.id, rangeKey)} aria-label={`Download ${row.name}`}>
                  <Download size={15} aria-hidden="true" />
                </Link>
              </td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}
